 create table PayTxnInfo (
    idTxn Integer not null PRIMARY KEY autoincrement,
	refNo Text,
	origRefNo Text,
	refundAmt String,
	exTraceNO Text,
    txnType Text not null,
	txnStatus Text,
	txnFlag Text,
	txnFlagMessage Text,
    salesAmt Text not null,
	termBatchNo Text,
	termTraceNo Text not null,
	txnTime Text,
    termTxnTime Text,
   	txnPartyId Text,
    txnPartyName Text,
	merchantId Text,
    merchantName Text,
	subPartyNo Text,
	subPartyName Text,
    shortPan Text,
    operNo Text,
	operName Text,
    refundAuditOper Text,
    longitude Double,
	latitude Double,
	bankAuthNo Text,
	memo Text,
	respCode Text,
	respMsg Text,
	ksn Text,
	imei Text,
	phone Text,
	appVersion Text,
	holPhoneNO Text,
	holMicroblog Text,
	holEmail Text,
	cardType Text,
	cardOrg Text,
	txnStatusDesc Text,
	tranPic Text,
	signPic Text,
	positionDesc Text,
	txnTypeDesc Text,
	issuerId Text,
	issuerName Text,
	txnAddress Text,
	txnId Text,
	salesCur Text,
	isRefundEnable Boolean,
	isCloudOrder Boolean,
	specLongitude Double,
	specLatitude Double,
	specCoordType Text,
	deviceId Text,
	updateTime Text not null,
	origTxnId Text,
	tranPicPath Text,
	signPicPath Text
	)