create table PurchaseOrderInfo (
    idOrder Integer not null PRIMARY KEY autoincrement,
	orderId Long,
	orderType Text,
	merchPartyId Text,
	merchOrderId Text,
	salesCur Text,
	salesAmt Text,
	terminalId Text,
	receiptNo Text,
	userName Text,
	personName Text,
	location Text,
	latitude Double,
	longitude Double,
	specCoordType Text,
	specLatitude Double,
	specLongitude Double,
	paymentMethod Text,
	paymentTxnId Text,
	orderTime Text,
	fulfillTime Text,
	refundTime Text,
	attr Text,
	status Text,
	salesChanType Text,
	crtTime Text,
	updateTime Text,
	items Text,
	compositeQueryField Text
)